FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-stretch-build AS build

WORKDIR /sensirion-hdlc
COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-stretch-run

WORKDIR /sensirion-hdlc
COPY tsconfig.json package.json ./
COPY --from=build /sensirion-hdlc/node_modules ./node_modules
COPY src ./src

CMD ["sleep","2h"]
